Test Pull
dkeye/pixelwars_v2 pull request #34
Opened 2022-11-14 10:59 UTC by Cyb3rTr0ll3737

Test Pull

2022-11-19 16:01 UTC, OnTike commented on BackendWebAPI/Controllers/IndexController.cs
>  namespace ReturnHTMLFromASPNETCoreWebAPI.Controllers
у нас за такие наименования неймспейсов в ж...

2022-11-19 16:21 UTC, dkeye requested changes

2022-11-19 16:21 UTC, dkeye commented on BackendWebAPI/Controllers/IndexController.cs
> +    [Route("Index")]
Ты бд подключал. Контроллер изменять не нужно было. В идеале - его нужно было удалить, так как html мы больше не возвращаем от слова совсем. Но это в следующей таске было бы.

2022-11-19 16:21 UTC, dkeye commented on BackendWebAPI/Controllers/PixelWarsController.cs
> +namespace BackendWebAPI.Controllers
В этой таске контроллер не нужен. Совсем. Нужна была модель к бд, подключение и два метода для получения/сохранения объекта (в таске так и написано).

2022-11-19 16:21 UTC, dkeye commented on BackendWebAPI/Models/PixelWarsDB.cs
> +    public class Test
Что за Test? Мы в бд будем хранить JSON, который будет содержать сетку координат и цветов. Если хотел конкретики, надо было назвать модель что-то вроде Grid и оставить два поля: ID и Squares.

2022-11-19 16:21 UTC, dkeye commented on BackendWebAPI/Program.cs
> +var builder = WebApplication.CreateBuilder(new WebApplicationOptions { WebRootPath = "../static" });  // �������� ����� ��� �������� �������
`// �������� ����� ��� �������� �������`

Не понял

2022-11-19 16:21 UTC, dkeye commented on BackendWebAPI/Properties/launchSettings.json
> +      "launchUrl": "Index",
зачем? Оно пока не нужно

2022-11-19 16:21 UTC, dkeye commented on BackendWebAPI/Services/PixelWarsService.cs
> +                bookStoreDatabaseSettings.Value.ConnectionString);
`Grid`
Смотри комментарий к модели

2022-11-19 16:21 UTC, dkeye commented on BackendWebAPI/Services/PixelWarsService.cs
> +        public async Task<List<Test>> GetAsync() =>
Методы для работы с моделью. Всё норм.

2022-11-19 16:21 UTC, dkeye commented on BackendWebAPI/appsettings.json
> +    "PixelWarsCollectionName": "Test"
Опять же, название коллекции такое себе

2022-11-19 16:29 UTC, dkeye commented on BackendWebAPI/Controllers/IndexController.cs
>  namespace ReturnHTMLFromASPNETCoreWebAPI.Controllers
> у нас за такие наименования неймспейсов в ж...

Молодой человек, у нас серьёзный проект

2022-11-19 21:17 UTC, Cyb3rTr0ll3737 commented on BackendWebAPI/appsettings.json
> +    "PixelWarsCollectionName": "Test"
название коллекции хотел позже поменять

2022-11-19 21:17 UTC, Cyb3rTr0ll3737 commented on BackendWebAPI/Program.cs
> +var builder = WebApplication.CreateBuilder(new WebApplicationOptions { WebRootPath = "../static" });  // �������� ����� ��� �������� �������
Коммент на русском, кодировка сбилась

2022-11-19 21:17 UTC, Cyb3rTr0ll3737 commented on BackendWebAPI/Models/PixelWarsDB.cs
> +    public class Test
ок, сделаю

2022-11-19 21:18 UTC, Cyb3rTr0ll3737 commented on BackendWebAPI/Controllers/PixelWarsController.cs
> +namespace BackendWebAPI.Controllers
У меня вся реализация обращения к БД идёт через контроллеры. Без них никак, насколько я понял

2022-11-19 21:18 UTC, Cyb3rTr0ll3737 commented on BackendWebAPI/Controllers/IndexController.cs
> +    [Route("Index")]
Я их соединю в один, если надо

2022-11-21 22:40 UTC, dkeye requested changes

2022-11-21 22:40 UTC, dkeye commented on BackendWebAPI/Controllers/PixelWarsController.cs
> +namespace BackendWebAPI.Controllers
Ну я могу удалить, если ты не можешь)

2022-11-21 22:40 UTC, dkeye commented on BackendWebAPI/appsettings.json
> +    "PixelWarsCollectionName": "Test"
Как поменяешь, делай реквест)

2022-11-21 22:41 UTC, dkeye commented on BackendWebAPI/Program.cs
> +var builder = WebApplication.CreateBuilder(new WebApplicationOptions { WebRootPath = "../static" });  // �������� ����� ��� �������� �������
Удали

2022-11-23 21:51 UTC, dkeye approved these changes

2022-11-23 21:51 UTC, dkeye approved these changes
Выглядит заебись, погнали дальше

2022-11-23 21:52 UTC, merged